---
- hosts: cameras
  gather_facts: no

  tasks:
    - name: Start recording
      shell: nohup python3 record.py > record.log &
      args:
        chdir: $HOME/Documents/topspin-tracker
      tags: start_record
    
    - name: Start Processing
      shell: nohup python3 replay.py > replay.log &
      args:
        chdir: $HOME/Documents/topspin-tracker 
      tags: start_replay


