---
- hosts: all
  gather_facts: no

  tasks:
    - name: Start recording on ball_detector
      shell: nohup python3 record.py > record.log &
      when: inventory_hostname in groups['ball_detector']
      args:
        chdir: ~/topspin-tracker/ball_detection/
    
    - name: Start pose_estimation on cam 1
      shell: nohup python3 run_pose_estimation.py --cam 1 -o test.mp4 > record_1.log &
      when: inventory_hostname in groups['pose_estimator_1']
      args:
        chdir: ~/topspin-tracker/pose_estimation/

    - name: Start pose_estimation on cam 2
      shell: nohup python3 run_pose_estimation.py --cam 2 -o test.mp4 > record_2.log &
      when: inventory_hostname in groups['pose_estimator_2']
      args:
        chdir: ~/topspin-tracker/pose_estimation/

    - name: Start vibrator
      shell: nohup python3 vibrator.py --cam 1 > vibrator.log &
      when: inventory_hostname in groups['pose_estimator_1']
      args:
        chdir: ~/topspin-tracker/pose_estimation/
