---
- hosts: all
  gather_facts: no

  tasks:
  - name: synchronize push ball detector folder
    synchronize:
      src: ../../
      dest: ~/topspin-tracker/
      delete: yes
      recursive: true

  # - name: pip install requirements
  #   shell: "python -m pip install -r requirements.txt"
  #   args:
  #     chdir: $HOME/Documents/topspin-tracker
