---
- hosts: all  
  gather_facts: no

  tasks:
  - name: stop all running python processes 
    shell: pkill -f "record.py" &
    ignore_errors: yes

  - name: stop all running python processes
    shell: pkill -f "replay.py" &
    ignore_errors: yes

  - name: stop all running python processes
    shell: pkill -f "vibrator.py" &
    ignore_errors: yes

  - name: stop all running python processes
    shell: pkill -f "run_pose_estimation.py" &
    ignore_errors: yes
