---
- hosts: ball_detector
  gather_facts: no

  tasks:
  - name: Click the picture
    shell: "python3 get_picture.py"
    args: 
      chdir: ~/topspin-tracker/ball_detection

  - name: Synchronize Pictures folder
    fetch:
      src: ~/topspin-tracker/ball_detection/pictures/table_image.png
      dest: ../server/pictures/
      flat: yes 
     
