---
- hosts: all
  gather_facts: no

  tasks:
    # - name: kill all the processes
    #   shell: pkill -2 -f "record.py" & pkill -2 -f "vibrator.py" & pkill -2 -f "run_pose_estimation.py" 
    - name: change file 
      shell: echo 1 > flex.tape
      args:
        chdir: ~/topspin-tracker/

    - name: copy vibrator csv from server to ball_detector
      when: inventory_hostname in groups['ball_detector']
      copy:
        src: ../server/timestamp_csvs/test.csv
        dest: ~/topspin-tracker/ball_detection/vibrator.csv
      
    - name: Start replay on ball_detector
      when: inventory_hostname in groups['ball_detector']
      shell: python3 replay.py 
      args:
        chdir: ~/topspin-tracker/ball_detection
      tags: start_replay
