---
- hosts: all
  gather_facts: no

  tasks:
    - name: kill all the processes
      shell: pkill -2 -f "record.py" & pkill -2 -f "vibrator.py" & pkill -2 -f "run_pose_estimation.py" 

    - name: copy vibrator csv from pose_estimator to ball_detector
      when: inventory_hostname in groups['pose_estimator']
      synchronize:
        src: ~/Documents/topspin-tracker/vibrator.csv 
        dest: ~/Documents/topspin-tracker
        mode: pull
      delegate_to: "{{groups['ball_detector'][0]}}"
      
    - name: Start replay on ball_detector
      when: inventory_hostname in groups['ball_detector']
      shell: nohup python3 replay.py > replay.log &
      args:
        chdir: ~/Documents/topspin-tracker 
      tags: start_replay
